"use client";

import { useActionState, useState, useTransition } from "react";
import Link from "next/link";
import { bulkImportGalleryAction, createLandingContentAction, deleteLandingContentAction, markAppointmentAttendanceAction, updateLandingContentAction } from "@/actions/admin";

type Appointment = { id: string; studentName: string; status: string; scheduledStart: Date; staffName: string | null };
type Gallery = { id: string; title: string; caption: string; imageUrl: string; imageAlt: string; isPublished: boolean };
type Leader = { id: string; name: string; position: string; imageUrl: string; imageAlt: string; summary: string; biography: unknown; isPublished: boolean };
type Announcement = { id: string; title: string; summary: string; content: string; imageUrl: string | null; isPublished: boolean };

const orangeButton = "rounded-xl bg-[#FF7F24] px-4 py-2.5 text-xs font-extrabold text-[#0A0A1A] transition hover:bg-[#40297B] hover:text-white disabled:opacity-50";
const input = "w-full rounded-xl border border-white/10 bg-white/[.06] px-3 py-2.5 text-sm text-white outline-none focus:border-[#FF7F24]";

function ContentForm({ kind, title, fields }: { kind: string; title: string; fields: { name: string; label: string; textarea?: boolean; required?: boolean }[] }) {
  const [state, action, pending] = useActionState(async (_: { success?: boolean; error?: string } | null, data: FormData) => createLandingContentAction(data), null);
  return <form action={action} className="rounded-2xl border border-white/10 bg-[#101023] p-5 space-y-3">
    <input type="hidden" name="kind" value={kind} />
    <div><h3 className="font-bold text-white">{title}</h3><p className="mt-1 text-xs text-gray-500">Changes are saved to the CMS and published content can be updated without a deployment.</p></div>
    {fields.map((field) => <label key={field.name} className="block text-xs font-semibold text-gray-300">{field.label}{field.textarea ? <textarea name={field.name} required={field.required} className={`${input} mt-1 min-h-20`} /> : <input name={field.name} required={field.required} className={`${input} mt-1`} />}</label>)}
    <label className="flex items-center gap-2 text-xs text-gray-300"><input type="checkbox" name="isPublished" defaultChecked className="accent-[#FF7F24]" /> Publish immediately</label>
    {state?.error && <p className="text-xs text-red-300">{state.error}</p>}{state?.success && <p className="text-xs text-emerald-300">Saved successfully.</p>}
    <button className={orangeButton} disabled={pending}>{pending ? "Saving..." : "Save"}</button>
  </form>;
}

export function AdminControlCenter({ appointments, gallery, leadership, announcements }: { appointments: Appointment[]; gallery: Gallery[]; leadership: Leader[]; announcements: Announcement[] }) {
  const [active, setActive] = useState("overview");
  const [createSection, setCreateSection] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const nav = [
    ["overview", "fa-chart-line", "Overview"], ["website", "fa-window-maximize", "Landing page"], ["services", "fa-briefcase", "Career services"], ["appointments", "fa-calendar-check", "Appointments"], ["training", "fa-play-circle", "Skills training"], ["assessments", "fa-clipboard-check", "Readiness assessments"], ["opportunities", "fa-laptop-house", "Internships & jobs"], ["employers", "fa-building", "Employer engagement"], ["staff", "fa-user-tie", "Career staff"],
  ];
  const approve = (id: string, attended: boolean) => startTransition(async () => { await markAppointmentAttendanceAction(id, attended); });
  return <div className="grid gap-6 lg:grid-cols-[230px_1fr]">
    <aside className="h-fit rounded-2xl border border-white/10 bg-[#101023] p-3 lg:sticky lg:top-24">
      <p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[.18em] text-gray-500">Super Admin workspace</p>
      <nav className="space-y-1">{nav.map(([id, icon, label]) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs font-semibold transition ${active === id ? "bg-[#FF7F24] text-[#0A0A1A]" : "text-gray-300 hover:bg-[#40297B] hover:text-white"}`}><i className={`fas ${icon} w-4`} />{label}</button>)}</nav>
      <div className="mt-4 border-t border-white/10 pt-4"><Link href="/" className="flex items-center gap-2 px-3 text-xs text-gray-400 hover:text-[#FF7F24]"><i className="fas fa-external-link-alt" /> View public site</Link></div>
    </aside>
    <section className="min-w-0 space-y-5">
      {active === "overview" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[["Website CMS", "Edit landing page sections, gallery, leadership and updates", "website"], ["Appointments", `${appointments.length} requests and scheduled sessions`, "appointments"], ["Student services", "Approve attendance and activate career tools", "services"], ["Training videos", "Manage YouTube employability lessons", "training"], ["Assessments", "Build readiness questions and recommendations", "assessments"], ["Opportunities", "Publish internships, jobs and career fairs", "opportunities"]].map(([title, description, id]) => <button key={id} onClick={() => setActive(id)} className="rounded-2xl border border-white/10 bg-[#101023] p-5 text-left transition hover:-translate-y-1 hover:border-[#FF7F24]/60"><i className="fas fa-arrow-right float-right text-[#FF7F24]" /><h3 className="font-bold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-gray-400">{description}</p></button>)}</div>}
      {active === "website" && <div className="space-y-8"><div className="grid gap-5 xl:grid-cols-3"><CreateCard title="Gallery" count={gallery.length} onClick={() => setCreateSection(createSection === "gallery" ? null : "gallery")} /> <CreateCard title="Leadership" count={leadership.length} onClick={() => setCreateSection(createSection === "leadership" ? null : "leadership")} /> <CreateCard title="Updates" count={announcements.length} onClick={() => setCreateSection(createSection === "announcement" ? null : "announcement")} /></div>{createSection === "gallery" && <><ContentForm kind="gallery" title="Create gallery item" fields={[{ name: "title", label: "Title", required: true }, { name: "imageUrl", label: "Image URL", required: true }, { name: "imageAlt", label: "Alt text" }, { name: "caption", label: "Caption", textarea: true, required: true }]} /><BulkGalleryImport /></>}{createSection === "leadership" && <ContentForm kind="leadership" title="Create leadership profile" fields={[{ name: "name", label: "Name", required: true }, { name: "position", label: "Position", required: true }, { name: "imageUrl", label: "Profile image URL", required: true }, { name: "summary", label: "Short biography", textarea: true, required: true }, { name: "biography", label: "Full biography (one paragraph per line)", textarea: true, required: true }]} />}{createSection === "announcement" && <ContentForm kind="announcement" title="Create update" fields={[{ name: "title", label: "Title", required: true }, { name: "summary", label: "Summary", required: true }, { name: "content", label: "Content", textarea: true, required: true }, { name: "imageUrl", label: "Optional image URL" }]} />}<LandingContentCrud gallery={gallery} leadership={leadership} announcements={announcements} /></div>}
      {active === "services" && <div className="grid gap-5 xl:grid-cols-2"><ContentForm kind="service" title="Add career service" fields={[{ name: "title", label: "Service name", required: true }, { name: "slug", label: "Slug", required: true }, { name: "summary", label: "Summary", required: true }, { name: "description", label: "Description", textarea: true }, { name: "icon", label: "Font Awesome icon (e.g. fa-file-alt)" }]} /><div className="rounded-2xl border border-white/10 bg-[#101023] p-5"><h3 className="font-bold text-white">Service access rule</h3><p className="mt-2 text-sm leading-6 text-gray-400">Career staff assess each student. Super Admin can review the resulting entitlements from the staff workspace. Approved attendance can activate the student’s remaining career services.</p><button onClick={() => setActive("appointments")} className={`${orangeButton} mt-4`}>Review attendance</button></div></div>}
      {active === "training" && <ContentForm kind="training" title="Add YouTube skills training video" fields={[{ name: "title", label: "Video title", required: true }, { name: "category", label: "Category", required: true }, { name: "videoUrl", label: "YouTube URL", required: true }, { name: "instructor", label: "Instructor" }, { name: "description", label: "Description", textarea: true, required: true }]} />}
      {active === "appointments" && <div className="rounded-2xl border border-white/10 bg-[#101023] p-5"><h2 className="text-xl font-extrabold text-white">Appointment requests and attendance</h2><p className="mt-1 text-sm text-gray-400">Review requests, then approve attendance after the Career Officer completes the consultation.</p><div className="mt-5 space-y-3">{appointments.length === 0 ? <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-gray-500">No appointment requests yet.</p> : appointments.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-xl border border-white/10 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-white">{item.studentName}</p><p className="text-xs text-gray-400">{new Date(item.scheduledStart).toLocaleString()} · {item.staffName || "Unassigned"}</p><span className="mt-2 inline-flex rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold uppercase text-[#FF7F24]">{item.status}</span></div><div className="flex gap-2"><button disabled={pending} onClick={() => approve(item.id, true)} className={orangeButton}>Approve attendance</button><button disabled={pending} onClick={() => approve(item.id, false)} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-bold text-gray-300 hover:border-[#40297B] hover:bg-[#40297B] hover:text-white">No show</button></div></div>)}</div></div>}
      {active === "assessments" && <Placeholder title="Job readiness assessments" body="Create assessment templates, questions, attempts, scores and recommendations from the assessment workspace." />}
      {active === "opportunities" && <Placeholder title="Virtual internships, job board and Career Fair Management" body="Publish opportunities with employer, deadline, location, application method and event details." />}
      {active === "employers" && <Placeholder title="Employer engagement" body="Manage partner organizations, announcements, career events and employer opportunities." />}
      {active === "staff" && <Placeholder title="Career staff" body="Use the Career Officers section below to create, activate and disable staff accounts. Public registration remains student-only." />}
    </section>
  </div>;
}

function Placeholder({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-white/10 bg-[#101023] p-6"><h2 className="text-xl font-extrabold text-white">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-gray-400">{body}</p><span className="mt-5 inline-flex rounded-full border border-[#FF7F24]/30 bg-[#FF7F24]/10 px-3 py-1.5 text-xs font-bold text-[#FF7F24]">Module ready for content</span></div>; }

function CreateCard({ title, count, onClick }: { title: string; count: number; onClick: () => void }) { return <button type="button" onClick={onClick} className="rounded-2xl border border-white/10 bg-[#101023] p-5 text-left transition hover:border-[#FF7F24]/60 hover:bg-[#40297B]"><div className="flex items-center justify-between"><span className="text-sm font-extrabold text-white">{title}</span><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold text-[#FF7F24]">{count} records</span></div><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#FF7F24]">Create new <i className="fas fa-plus" /></span></button>; }

function BulkGalleryImport() {
  const [payload, setPayload] = useState("");
  const [state, action, pending] = useActionState(bulkImportGalleryAction, null);
  return <form action={action} className="rounded-2xl border border-[#FF7F24]/30 bg-[#101023] p-5 space-y-3">
    <div><h3 className="font-bold text-white">Bulk import Cloudinary gallery</h3><p className="mt-1 text-xs text-gray-400">Upload the cloudinary-assets.json file generated by the resolver. Existing image URLs are skipped automatically.</p></div>
    <input type="hidden" name="payload" value={payload} />
    <input type="file" accept=".json,application/json" className="block w-full text-xs text-gray-300 file:mr-3 file:rounded-lg file:border-0 file:bg-[#FF7F24] file:px-3 file:py-2 file:font-bold file:text-[#0A0A1A]" onChange={async (event) => { const file = event.target.files?.[0]; if (file) setPayload(await file.text()); }} />
    {payload && <p className="text-xs text-emerald-300">Asset file loaded and ready to import.</p>}
    {state?.error && <p className="text-xs text-red-300">{state.error}</p>}{state?.success && <p className="text-xs text-emerald-300">{state.message}</p>}
    <button disabled={pending || !payload} className={orangeButton}>{pending ? "Importing..." : "Import gallery assets"}</button>
  </form>;
}

function LandingContentCrud({ gallery, leadership, announcements }: { gallery: Gallery[]; leadership: Leader[]; announcements: Announcement[] }) {
  return <div className="space-y-6"><CrudGroup title={`Gallery (${gallery.length})`} kind="gallery" items={gallery} /><CrudGroup title={`Leadership (${leadership.length})`} kind="leadership" items={leadership} /><CrudGroup title={`Updates (${announcements.length})`} kind="announcement" items={announcements} /></div>;
}

function CrudGroup({ title, kind, items }: { title: string; kind: string; items: (Gallery | Leader | Announcement)[] }) {
  return <section className="rounded-2xl border border-white/10 bg-[#101023] p-5"><h2 className="text-lg font-extrabold text-white">{title}</h2>{items.length === 0 ? <p className="mt-3 rounded-xl border border-dashed border-white/10 p-6 text-sm text-gray-500">No records yet. Use the creation form above.</p> : <div className="mt-4 grid gap-4 xl:grid-cols-2">{items.map((item) => <EditableContent key={item.id} kind={kind} item={item} />)}</div>}</section>;
}

function EditableContent({ kind, item }: { kind: string; item: Gallery | Leader | Announcement }) {
  const [editing, setEditing] = useState(false);
  const [state, action, pending] = useActionState(async (_: { success?: boolean; error?: string } | null, data: FormData) => { const result = await updateLandingContentAction(data); if (result.success) setEditing(false); return result; }, null);
  const [deleting, startDelete] = useTransition();
  const leader = kind === "leadership" ? item as Leader : null;
  const gallery = kind === "gallery" ? item as Gallery : null;
  const announcement = kind === "announcement" ? item as Announcement : null;
  const biography = leader ? (Array.isArray(leader.biography) ? leader.biography.join("\n") : String(leader.biography || "")) : "";
  const remove = () => { if (window.confirm("Delete this public content?")) startDelete(async () => { await deleteLandingContentAction(kind, item.id); }); };
  if (!editing) return <article className="rounded-xl border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{gallery?.title || leader?.name || announcement?.title}</h3><p className="mt-1 line-clamp-2 text-xs text-gray-400">{gallery?.caption || leader?.position || announcement?.summary}</p><span className={`mt-3 inline-flex rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.isPublished ? "bg-emerald-500/10 text-emerald-300" : "bg-white/10 text-gray-400"}`}>{item.isPublished ? "Published" : "Draft"}</span></div><div className="flex gap-2"><button onClick={() => setEditing(true)} className="rounded-lg border border-[#FF7F24]/40 px-3 py-1.5 text-xs font-bold text-[#FF7F24] hover:bg-[#40297B] hover:text-white">Edit</button><button onClick={remove} disabled={deleting} className="rounded-lg border border-red-500/30 px-3 py-1.5 text-xs font-bold text-red-300 hover:bg-red-500/20">Delete</button></div></div></article>;
  return <form action={action} className="rounded-xl border border-[#FF7F24]/40 bg-[#0A0A1A] p-4 space-y-3"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="kind" value={kind} />{kind === "gallery" && <><Field name="title" label="Title" value={gallery?.title} /><Field name="imageUrl" label="Image URL" value={gallery?.imageUrl} /><Field name="imageAlt" label="Alt text" value={gallery?.imageAlt} /><Field name="caption" label="Caption" value={gallery?.caption} textarea /></>}{kind === "leadership" && <><Field name="name" label="Name" value={leader?.name} /><Field name="position" label="Position" value={leader?.position} /><Field name="imageUrl" label="Image URL" value={leader?.imageUrl} /><Field name="imageAlt" label="Alt text" value={leader?.imageAlt} /><Field name="summary" label="Summary" value={leader?.summary} textarea /><Field name="biography" label="Biography" value={biography} textarea /></>}{kind === "announcement" && <><Field name="title" label="Title" value={announcement?.title} /><Field name="summary" label="Summary" value={announcement?.summary} /><Field name="content" label="Content" value={announcement?.content} textarea /><Field name="imageUrl" label="Image URL" value={announcement?.imageUrl || ""} /></>}<label className="flex items-center gap-2 text-xs text-gray-300"><input type="checkbox" name="isPublished" defaultChecked={item.isPublished} className="accent-[#FF7F24]" /> Published</label>{state?.error && <p className="text-xs text-red-300">{state.error}</p>}<div className="flex gap-2"><button disabled={pending} className={orangeButton}>{pending ? "Saving..." : "Save changes"}</button><button type="button" onClick={() => setEditing(false)} className="rounded-xl border border-white/15 px-4 py-2 text-xs font-bold text-gray-300 hover:bg-[#40297B] hover:text-white">Cancel</button></div></form>;
}

function Field({ name, label, value, textarea }: { name: string; label: string; value?: string; textarea?: boolean }) { return <label className="block text-xs font-semibold text-gray-300">{label}{textarea ? <textarea name={name} defaultValue={value} required className={`${input} mt-1 min-h-16`} /> : <input name={name} defaultValue={value} required className={`${input} mt-1`} />}</label>; }
